GET  http://localhost:3001/api/user/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNTE4ZGRjOGM5NTE0NDcxYzE1MWEyNyIsImVtYWlsIjoibm90YWRtaW5AZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY2NjI5NDM4NCwiZXhwIjoxNjY2Mjk3OTg0fQ.-S-Ew88gxfuly4IDJ8gqBiUL643zLTHkqqxSoeZRraI