GET http://localhost:3001/api/user/register 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNGYxYzQxMzQ2NjI5NzNmYmVhODJmYiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjY2MTMwOTM3LCJleHAiOjE2NjYxMzQ1Mzd9.GNXs4KAxC0aAwWNmenQi7UDWxqDpS28Ab3yFBwWPGFY
