POST http://localhost:3001/api/user/register 
Content-Type: application/json


{     
    "email": "notadmin@gmail.com",     
    "password": "password123",     
    "name": "notadmin",     
    "lastname": "notadmin"
}
